package com.ap_graphics.model.enums;

public enum SoundEffectType
{
    ARROW_FLY_3_3("audio/sfx/Arrow Fly 3_3.wav"),
    BAT_DEATH_02("audio/sfx/Bat_Death_02.wav"),
    BIG_WEAPON_WHOOSH("audio/sfx/Big_Weapon_Whoosh.wav"),
    BIG_WEAPON_WHOOSH_WITH_ECHO("audio/sfx/Big_Weapon_Whoosh_With_Echo.wav"),
    BLOOD_SPLASH_QUICK_01("audio/sfx/Blood_Splash_Quick_01.wav"),
    BUFF_BEASTSPOWER("audio/sfx/Buff_BeastsPower.wav"),
    BUFF_INTELLIGENCE("audio/sfx/Buff_Intelligence.wav"),
    BUFF_POSITIVE("audio/sfx/Buff_Positive.wav"),
    BUFF_POWER_UP_01("audio/sfx/Buff_Power_Up_01.wav"),
    COINS_10("audio/sfx/Coins (10).wav"),
    COUNT_PRIZE_SINGLE_TICK("audio/sfx/Count Prize (Single Tick).wav"),
    CRYSTAL_REWARD_TICK("audio/sfx/Crystal Reward Tick.wav"),
    DAGGER_WHOOSH_02("audio/sfx/Dagger_Whoosh_02.wav"),
    DAGGER_WHOOSH_03("audio/sfx/Dagger_Whoosh_03.wav"),
    DAGGER_WHOOSH_04("audio/sfx/Dagger_Whoosh_04.wav"),
    DEBUFF_BEASTS("audio/sfx/Debuff_Beasts.wav"),
    DEBUFF_POSITIVE("audio/sfx/Debuff_Positive.wav"),
    DEBUFF_SPEED("audio/sfx/Debuff_Speed.wav"),
    DRUM_ROLL_3("audio/sfx/Drum Roll (3).wav"),
    EXPLOSION_BLOOD_01("audio/sfx/Explosion_Blood_01.wav"),
    FOOTSTEPS_CASUAL_GRASS_01("audio/sfx/Footsteps_Casual_Grass_01.wav"),
    FOOTSTEPS_CASUAL_GRASS_02("audio/sfx/Footsteps_Casual_Grass_02.wav"),
    FOOTSTEPS_CASUAL_GRASS_03("audio/sfx/Footsteps_Casual_Grass_03.wav"),
    HEAL_SHORT("audio/sfx/Heal_Short.wav"),
    ITEM_LOCK_1("audio/sfx/Item Lock (1).wav"),
    LIGHTNING_SPELLL_18("audio/sfx/Lightning Spelll 18.wav"),
    LIGHTNING_SPELLL_19("audio/sfx/Lightning Spelll 19.wav"),
    MONSTER_2_ATTACK_QUICK_01_WITH_ECHO("audio/sfx/Monster_2_Attack_Quick_01_WITH_ECHO.wav"),
    MONSTER_2_RECIEVEATTACK_HIGHINTENSITY_01("audio/sfx/Monster_2_RecieveAttack_HighIntensity_01.wav"),
    OBTAIN_POINTS_01("audio/sfx/Obtain_Points_01.wav"),
    OBTAIN_POINTS_02("audio/sfx/Obtain_Points_02.wav"),
    OBTAIN_POINTS_03("audio/sfx/Obtain_Points_03.wav"),
    OBTAIN_POINTS_04("audio/sfx/Obtain_Points_04.wav"),
    OBTAIN_POINTS_05("audio/sfx/Obtain_Points_05.wav"),
    OBTAIN_POINTS_06("audio/sfx/Obtain_Points_06.wav"),
    POP_3("audio/sfx/Pop (3).wav"),
    PRETTY_DUNGEON_LOOP("audio/sfx/Pretty Dungeon LOOP.wav"),
    SHIELD_POISON("audio/sfx/Shield_Poison.wav"),
    SPECIAL_AND_POWERUP_10("audio/sfx/Special & Powerup (10).wav"),
    SPECIAL_AND_POWERUP_11("audio/sfx/Special & Powerup (11).wav"),
    SPECIAL_AND_POWERUP_13("audio/sfx/Special & Powerup (13).wav"),
    SPECIAL_AND_POWERUP_16("audio/sfx/Special & Powerup (16).wav"),
    SPECIAL_AND_POWERUP_17("audio/sfx/Special & Powerup (17).wav"),
    SPECIAL_AND_POWERUP_19("audio/sfx/Special & Powerup (19).wav"),
    SPECIAL_AND_POWERUP_24("audio/sfx/Special & Powerup (24).wav"),
    SPECIAL_AND_POWERUP_8("audio/sfx/Special & Powerup (8).wav"),
    SPELLBOOK_NEWSPELL_01("audio/sfx/SpellBook_NewSpell_01.wav"),
    SPELL_AIR_03("audio/sfx/Spell_Air_03.wav"),
    SPELL_AIR_SMALL_WHOOSH_03("audio/sfx/Spell_Air_Small_Whoosh_03.wav"),
    SPELL_BLACKMAGIC_SHORT_01("audio/sfx/Spell_BlackMagic_Short_01.wav"),
    SPELL_BLACKMAGIC_SHORT_02("audio/sfx/Spell_BlackMagic_Short_02.wav"),
    SPELL_BLACKMAGIC_SHORT_03("audio/sfx/Spell_BlackMagic_Short_03.wav"),
    SPELL_CURSE_01("audio/sfx/Spell_Curse_01.wav"),
    SPELL_EXPLOSION_MAGIC_02("audio/sfx/Spell_Explosion_Magic_02.wav"),
    SPELL_FIRE_IMPACT_01("audio/sfx/Spell_Fire_Impact_01.wav"),
    SPELL_FIRE_SMALL_WHOOSH_01("audio/sfx/Spell_Fire_Small_Whoosh_01.wav"),
    SPELL_FIRE_SMALL_WHOOSH_02("audio/sfx/Spell_Fire_Small_Whoosh_02.wav"),
    SPELL_FIRE_SMALL_WHOOSH_03("audio/sfx/Spell_Fire_Small_Whoosh_03.wav"),
    SPELL_FIRE_WHOOSH_02("audio/sfx/Spell_Fire_Whoosh_02.wav"),
    SPELL_FREEZE("audio/sfx/Spell_Freeze.wav"),
    SPELL_ICESPEAR_03("audio/sfx/Spell_IceSpear_03.wav"),
    SPELL_ICE_IMPACT_03("audio/sfx/Spell_Ice_Impact_03.wav"),
    SPELL_PROJECTILE_SHADOW_01("audio/sfx/Spell_Projectile_Shadow_01.wav"),
    SPELL_RECHARGE_VERSION_01("audio/sfx/Spell_Recharge_Version_01.wav"),
    SPELL_WATER_01("audio/sfx/Spell_Water_01.wav"),
    SPELL_WATER_02("audio/sfx/Spell_Water_02.wav"),
    SPELL_WIND_02("audio/sfx/Spell_Wind_02.wav"),
    STANDARD_WEAPON_WHOOSH_01("audio/sfx/Standard_Weapon_Whoosh_01.wav"),
    STANDARD_WEAPON_WHOOSH_02("audio/sfx/Standard_Weapon_Whoosh_02.wav"),
    STANDARD_WEAPON_WHOOSH_03("audio/sfx/Standard_Weapon_Whoosh_03.wav"),
    SWITCH_8("audio/sfx/Switch (8).wav"),
    TORCH_WHOOSH_02("audio/sfx/Torch_Whoosh_02.wav"),
    UI_CLICK_36("audio/sfx/UI Click 36.wav"),
    WASTELAND_COMBAT_LOOP("audio/sfx/Wasteland Combat Loop.wav"),
    WEAPON_SHOTGUN_RELOAD("audio/sfx/Weapon_Shotgun_Reload.wav"),
    WEAPON_VARIOUS_WHOOSHES_MOVEMENTS_01("audio/sfx/Weapon_Various_Whooshes_Movements_01.wav"),
    WEAPON_VARIOUS_WHOOSHES_MOVEMENTS_04("audio/sfx/Weapon_Various_Whooshes_Movements_04.wav"),
    WHOOSH_12_2("audio/sfx/Whoosh 12_2.wav"),
    WHOOSH_9_5("audio/sfx/Whoosh 9_5.wav"),
    YOU_LOSE_4("audio/sfx/You Lose (4).wav"),
    YOU_WIN_2("audio/sfx/You Win (2).wav"),
    DEADLY_LAZAR_SHOT_24("audio/sfx/deadly_lazar_shot_24.wav"),
    SFX_LOWHEALTH_ALARMLOOP1("audio/sfx/sfx_lowhealth_alarmloop1.wav"),
    SFX_SOUNDS_IMPACT1("audio/sfx/sfx_sounds_impact1.wav"),
    SINGLE_SHOT("audio/sfx/single_shot.wav");

    private final String filePath;

    SoundEffectType(String filePath)
    {
        this.filePath = filePath;
    }

    public String getFilePath()
    {
        return filePath;
    }
}
